# Generated by Django 4.2.6 on 2023-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
